---
- hosts: webservers
  tasks:
    - name: Make sure all OS patches are applied
      shell: yum update -y
      become: yes 
    - name: Install our needed packages for AWS Linux
      shell: yum install -y git
      become: yes
